version: "3"

services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    networks: 
      - node-network
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - mongo
    restart: always
    ports:
      - 3001:3001
    networks: 
      - node-network

networks: 
  node-network:
#    external: true
    driver: bridge